# -*- coding: utf-8 -*-
"""EE3900-GATE-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PngaJd9Z-oE24OeBz6piXaghE5B8O7-q
"""

import numpy as np
import matplotlib.pyplot as plt

t1=np.linspace(-2,2,5)

# Input Signal
x=[0,0,1,0,0]

# h1(t) and h2(t)
h1 = [0,2,1,0,0]
h2 = [0,1,2,0,0]

# Plotting Input Signal
plt.stem(t1,x,use_line_collection=True)
plt.ylabel('$x$')
plt.xlabel('$t$')
plt.show()

# Plotting h1
plt.stem(t1,h1,use_line_collection=True)
plt.ylabel('$h1$')
plt.xlabel('$t$')
plt.show()

# Plotting h2
plt.stem(t1,h2,use_line_collection=True)
plt.ylabel('$h2$')
plt.xlabel('$t$')
plt.show()

t2=np.linspace(-6,6,13)


# Cascade System

# Using 2 Convolutions one after other
# Convolution of Input x and h1 gives output y1
y1 = np.convolve(x,h1)

# Convolution of output y1 and h2 gives final output y2
y2 = np.convolve(y1,h2)

# y2 is Final output after 2 convolutions in Cascade System
print("y2 = ",y2)

# Plotting y2
plt.stem(t2,y2,use_line_collection=True)
plt.ylabel('$y2$')
plt.xlabel('$t$')
plt.show()

# Using convolution of h1 and h2
# Converting Convolution of h1 and h2 into h
h = np.convolve(h1,h2)

# Convolution of Input x and h gives final output y
y = np.convolve(x,h)

# y is the Final ouput 
print("y = ",y)

# Plotting y
plt.stem(t2,y,use_line_collection=True)
plt.ylabel('$y$')
plt.xlabel('$t$')
plt.show()

print("\nThe above two outputs(y2 and y) are the same.\n")
print("Therefore, when Two systems with impulse responses h1(t) and h2(t) are connected in Cascade,")
print("the overall impulse response of the Cascaded system is given by convolution of h1(t) and h2(t)")