# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eBBqtafZaE6cnG0-X5iU-8-vQxDMZoa8
"""

import numpy as np
import matplotlib.pyplot as plt
import math

# Generating points on a circle
def circ_gen(O,r):
	len = 50
	theta = np.linspace(0,2*np.pi,len)
	x_circ = np.zeros((2,len))
	x_circ[0,:] = r*np.cos(theta)
	x_circ[1,:] = r*np.sin(theta)
	x_circ = (x_circ.T + O).T
	return x_circ

# Generating a Circle of radius 3
x_circ = circ_gen(0,3)

# Plotting the Circle
plt.plot(x_circ[0,:],x_circ[1,:],label='$Circle$')


# Generating the line points
def line_gen(X,Y):
  len =10
  x = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = X + lam_1[i]*(Y-X)
    x[:,i]= temp1.T
  return x

# Generating points on the circle
O = np.array([0,0])
P = np.array([0,3])
Q = np.array([0,-3])
R = np.array([3,0])
S = np.array([-3,0])

# PQ, RS are Diagonals (Diameters) which are perpendicular
# PR, RQ, QS, SP are sides of the Quadrilateral PRQS
# Generating the lines PQ, RS, PR, RQ, QS, SP
x_PQ = line_gen(P,Q)
x_RS = line_gen(R,S)
x_PR = line_gen(P,R)
x_RQ = line_gen(R,Q)
x_QS = line_gen(Q,S)
x_SP = line_gen(S,P)

# Plotting all the lines PQ, RS, PR, RQ, QS, SP
plt.plot(x_PQ[0,:],x_PQ[1,:],label='$PQ$')
plt.plot(x_RS[0,:],x_RS[1,:],label='$RS$')
plt.plot(x_PR[0,:],x_PR[1,:],label='$PR$')
plt.plot(x_RQ[0,:],x_RQ[1,:],label='$RQ$')
plt.plot(x_QS[0,:],x_QS[1,:],label='$QS$')
plt.plot(x_SP[0,:],x_SP[1,:],label='$SP$')

# Labelling Points
plt.plot(O[0], O[1], 'o')
plt.text(O[0] - (0.4), O[1] + (0.1) , 'O')
plt.plot(P[0], P[1], 'o')
plt.text(P[0] + (0.1), P[1] + (0.05) , 'P')
plt.plot(Q[0], Q[1], 'o')
plt.text(Q[0] - (0.3), Q[1] - (0.25) , 'Q')
plt.plot(R[0], R[1], 'o')
plt.text(R[0] + (0.1), R[1] - (0.2) , 'R')
plt.plot(S[0], S[1], 'o')
plt.text(S[0] - (0.3), S[1] - (0.2) , 'S')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best',fontsize=8)
plt.grid()
plt.axis('equal')
plt.show()

# Since the Diagonals(PQ and RS) of the Quadrilateral PRQS are perpendicular, of equal length and bisecting each other, hence it is a Square which can be verified from the figure
# Hence, the Quadrilateral PRQS is a Square when the Diameters(PQ and RS) are perpendicular to each other.